replicaCount: 2

image:
  repository: ahgpeu6po/ecommerce-app
  tag: latest
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

service:
  type: ClusterIP
  port: 4000

mongo:
  replicaCount: 1
  image:
    repository: mongo
    tag: "5.0"
    pullPolicy: IfNotPresent
  servicePort: 27017

secret:
  DB_USER: mongo-user
  DB_PASSWORD: mongo-password
  STRIPE_SECRET_KEY: stripe_key

config:
  MONGODB_URI: "mongodb://mongo-user:mongo-password@mongo-service:27017"