apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-app-deployment
  labels:
    app: ecommerce-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecommerce-app
  template:
    metadata:
      labels:
        app: ecommerce-app
    spec:
      containers:
        - name: ecommerce-app
          image: ahgpeu6po/ecommerce-app:latest
          ports:
            - containerPort: 4000
          
          env:
          - name: USER_NAME
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: DB_USER
          - name: USER_PWD
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: DB_PASSWORD
          - name: MONGODB_URI
            valueFrom:
              configMapKeyRef:
                name: mongo-config
                key: mongo-url
          - name: STRIPE_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: STRIPE_SECRET_KEY

          livenessProbe:
            httpGet:
              path: /health
              port: 4000
            initialDelaySeconds: 10
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 5