apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecommerce-app
  template:
    metadata:
      labels:
        app: ecommerce-app
    spec:
      containers:
        - name: ecommerce-app
          image: ahgpeu6po/ecommerce-app:latest
          ports:
            - containerPort: 4000

          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret

          env:
            - name: MONGODB_URI
              value: "mongodb://root:$(DB_PASSWORD)@db:27017/mydb?authSource=admin"

            - name: PORT
              value: "4000"

          livenessProbe:
            httpGet:
              path: /health
              port: 4000
            initialDelaySeconds: 10
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 5