apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-app
  namespace: ecommerce
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecommerce-app
  template:
    metadata:
      labels:
        app: ecommerce-app
    spec:
      containers:
      - name: app
        image: ghcr.io/ksssks/ecommerce-app:latest
        ports:
        - containerPort: 4000
        env:
        - name: MONGODB_URI
          value: "mongodb://root:example@mongo:27017/mydb?authSource=admin"
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: PORT
        - name: STRIPE_SECRET_KEY
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: STRIPE_SECRET_KEY
        livenessProbe:
          httpGet:
            path: /health
            port: 4000
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 4000
          initialDelaySeconds: 5
          periodSeconds: 5